language: go

install:
  - ./scripts/install-dependencies

before_script:
  - go get -v

script:
  - sudo ldconfig
  - "export LD_LIBRARY_PATH=/usr/lib64:/usr/lib:/usr/local/lib:/usr/local/lib64:$LD_LIBRARY_PATH"
  - go test -v

after_failure:
  - ./scripts/after-failure
after_error:
  - ./scripts/after-failure

go:
  - 1.3
