language: go

before_install:
  - "export DISPLAY=:99.0"

install:
  - ./scripts/install-dependencies

before_script:
  - go get -v

script:
  - sudo ldconfig
  - "export LD_LIBRARY_PATH=/usr/lib64:/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH"
  - xvfb-run -s "-screen 0 1024x768x16 +extension GLX +render -noreset" go test -v

after_failure:
  - ./scripts/after-failure
after_error:
  - ./scripts/after-failure

go:
  - 1.3
