language: go

install:
  - ./scripts/install-dependencies

before_script:
 - go get -v

script:
 - go test -v

after_failure:
  - ./scripts/after-failure
after_error:
  - ./scripts/after-failure

go:
  - 1.3
