#! /usr/bin/env bash

# Error log
erl() {
  at "  ""$@"
  "$@" &>> error.log
  return $?
}

at() {
  echo "--" "$@" | tee -a error.log
  date +%H:%M:%S.%N &>> error.log
}

die() {
  at "Failure: $@"
  exit 1
}

sudo apt-get update -qq

at "Installing eatmydata and pcregrep"
erl sudo apt-get install eatmydata pcregrep || die "Failed to install"

at "apt-get update -qq"
erl sudo eatmydata apt-get update -qq \
  || die "'apt-get update -qq' failed"

at "Installing dependencies"
erl sudo eatmydata apt-get install -qq \
  xorg-dev libglu1-mesa-dev \
  || die "Failed to install dependencies"

at "Install GLFW3"
erl wget http://downloads.sourceforge.net/project/glfw/glfw/3.0.4/glfw-3.0.4.zip
erl unzip glfw-3.0.4.zip
pushd glfw-3.0.4
  erl cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
  erl make
  erl sudo make install
popd

at "Installing GLEW"
erl wget http://downloads.sourceforge.net/project/glew/glew/1.11.0/glew-1.11.0.tgz
erl tar -xvf glew-1.11.0.tgz
pushd glew-1.11.0
  erl make
  erl sudo make install
  erl make clean
popd
