#!/bin/bash -e

echo "*** Installing dependencies ***"
sudo apt-get update -qq
sudo apt-get -y install xorg-dev libglu1-mesa-dev

echo "*** Installing GLFW3 ***"
wget http://downloads.sourceforge.net/project/glfw/glfw/3.0.4/glfw-3.0.4.zip
unzip glfw-3.0.4.zip
pushd glfw-3.0.4
  cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
  make
  sudo make install
popd

echo "*** Installing GLEW ***"
wget http://downloads.sourceforge.net/project/glew/glew/1.11.0/glew-1.11.0.tgz
tar -xvf glew-1.11.0.tgz
pushd glew-1.11.0
  make
  sudo make install
  make clean
popd
