#!/bin/bash -e

echo "*** Installing dependencies ***"
sudo apt-get update -qq
sudo apt-get install -qq \
  libglfw-dev libglew-dev mesa-utils inotify-tools xserver-xorg \
  libsdl1.2-dev libsdl-image1.2-dev \
  || die "Failed to install dependencies"

echo "*** Starting X ***"
sudo mkdir -p /tmp/.X11-unix

echo "*** Waiting for X to come up ***"
inotifywait -t 4 -r /tmp/.X11-unix

export DISPLAY=:0

echo "*** Fetching dependencies ***"
go get -d -v \
  || die "go get failed"
