#! /usr/bin/env bash

# Error log
erl() {
  at "  ""$@"
  "$@" &>> error.log
  return $?
}

at() {
  echo "--" "$@" | tee -a error.log
  date +%H:%M:%S.%N &>> error.log
}

die() {
  at "Failure: $@"
  exit 1
}

sudo apt-get update -qq

at "Installing eatmydata and pcregrep"
erl sudo apt-get install eatmydata pcregrep || die "Failed to install"

at "apt-get update -qq"
erl sudo eatmydata apt-get update -qq \
  || die "'apt-get update -qq' failed"

at "Installing dependencies"
erl sudo eatmydata apt-get install -qq \
  libglfw-dev libglew-dev mesa-utils inotify-tools xserver-xorg \
  libsdl1.2-dev libsdl-image1.2-dev \
  unzip build-essential cmake \
  xorg-dev libglu1-mesa-dev \
  || die "Failed to install dependencies"

at "Starting X"
erl sudo mkdir -p /tmp/.X11-unix
(sleep 0.5 && sudo X) &>> error.log &

at "Waiting for X to come up"
inotifywait -t 4 -r /tmp/.X11-unix

export DISPLAY=:0

at "Install GLFW3"
wget http://downloads.sourceforge.net/project/glfw/glfw/3.0.4/glfw-3.0.4.zip
unzip glfw-3.0.4.zip
pushd glfw-3.0.4
  cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON
  make
  sudo make install
popd

at "Fetching dependencies"
go get -d -v \
  || die "go get failed"
